package:
  name: "eztorch4conv"
  version: "0.0.1"

source:
  git_rev: v0.0.1
  git_url: https://github.com/RaulFD-creator/eztorch4conv

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - pytorch
    - pandas

about:
  home: https://github.com/RaulFD-creator/eztorch4conv
  license: BSD-3-Clause License 
  license_familY: BSD-3-Clause License 
  license_file: LICENSE
  summary: "A Python package with out of the box pytorch classes to easily design and train DCNN and MC-DCNN models. Currently on development. "
